
import React from 'react';
import { AlertTriangle, User, Calendar, Activity } from 'lucide-react';

interface MedicalReportData {
  patientAge: number;
  patientGender: string;
  boneDensity: number;
  corticalThickness: number;
  trabecularDensity: number;
  calciumLevel: number;
  boneType: string;
  porosity: number;
  zScore: number;
  thickness: number;
}

interface MedicalReportGeneratorProps {
  data: MedicalReportData;
  className?: string;
}

const MedicalReportGenerator = ({ data, className = "" }: MedicalReportGeneratorProps) => {
  const getRiskLevel = () => {
    const avgScore = (data.boneDensity + data.corticalThickness + data.trabecularDensity + data.calciumLevel) / 4;
    if (avgScore >= 75) return { level: 'Normal', color: 'bg-green-500', textColor: 'text-green-800' };
    if (avgScore >= 50) return { level: 'Riesgo moderado', color: 'bg-yellow-500', textColor: 'text-yellow-800' };
    return { level: 'Riesgo alto', color: 'bg-red-500', textColor: 'text-red-800' };
  };

  const risk = getRiskLevel();
  const hasFractures = data.boneDensity < 60 || data.corticalThickness < 50;

  return (
    <div className={`bg-white p-8 rounded-lg shadow-lg max-w-2xl mx-auto ${className}`}>
      {/* Header */}
      <div className="flex items-center mb-6">
        <div className="bg-red-500 rounded-full p-3 mr-4">
          <Activity className="h-8 w-8 text-white" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Resultado de tu examen óseo</h1>
        </div>
      </div>

      {/* Patient Info */}
      <div className="flex items-center mb-6">
        <User className="h-5 w-5 text-gray-600 mr-2" />
        <span className="text-lg text-gray-700">
          Paciente: {data.patientGender}, {data.patientAge} años
        </span>
      </div>

      {/* Risk Alert */}
      <div className={`${risk.color} text-white p-4 rounded-lg mb-6 flex items-center`}>
        <AlertTriangle className="h-6 w-6 mr-3" />
        <div>
          <h2 className="text-xl font-bold">{risk.level}</h2>
          <p className="text-sm opacity-90">
            {hasFractures ? "Riesgo de fracturas detectado." : "No hay fracturas detectadas."}
          </p>
        </div>
      </div>

      {/* Indicators */}
      <div className="mb-6">
        <h3 className="text-lg font-semibold text-gray-800 mb-4">Indicadores:</h3>
        <ul className="space-y-2 text-gray-700">
          <li>• Espesor del hueso: {data.thickness} mm ({data.thickness < 2 ? 'bajo' : data.thickness > 4 ? 'alto' : 'normal'})</li>
          <li>• Porosidad: {data.porosity}% ({data.porosity > 20 ? 'alto desgaste' : 'normal'})</li>
          <li>• Relación porosidad/espesor: {(data.porosity / data.thickness).toFixed(1)}</li>
          <li>• Z-score: {data.zScore > 0 ? '+' : ''}{data.zScore} (comparación con personas de tu edad)</li>
        </ul>
      </div>

      {/* Risk Scale */}
      <div className="mb-6">
        <div className="flex justify-between text-sm text-gray-600 mb-2">
          <span>Normal</span>
          <span>Riesgo alto</span>
        </div>
        <div className="h-6 bg-gradient-to-r from-green-500 via-yellow-500 to-red-500 rounded-full relative">
          <div 
            className="absolute top-1/2 transform -translate-y-1/2 w-4 h-4 bg-white border-4 border-red-500 rounded-full"
            style={{ left: `${Math.max(10, Math.min(90, 100 - (data.boneDensity + data.corticalThickness) / 2))}%` }}
          ></div>
        </div>
        <div className="flex justify-between text-xs text-gray-500 mt-1">
          <span>0,7</span>
          <span>-2,5</span>
        </div>
      </div>

      {/* Explanation */}
      <div className="bg-gray-50 p-4 rounded-lg">
        <h4 className="font-semibold text-gray-800 mb-2">¿Qué significa esto?</h4>
        <p className="text-gray-700 text-sm">
          {risk.level === 'Riesgo alto' 
            ? "Tu densidad ósea presenta señales de riesgo. Es importante que sigas un plan médico para fortalecer tus huesos y evitar fracturas."
            : risk.level === 'Riesgo moderado'
            ? "Tu densidad ósea muestra algunos signos de debilitamiento. Se recomienda seguimiento médico y medidas preventivas."
            : "Tu densidad ósea se encuentra en rangos normales. Mantén hábitos saludables para preservar la salud ósea."
          }
        </p>
      </div>

      {/* Generated by PetitOs */}
      <div className="mt-6 pt-4 border-t border-gray-200 text-center">
        <p className="text-xs text-gray-500">
          Generado por PetitOs - Análisis de Densidad Ósea
        </p>
        <p className="text-xs text-gray-400">
          {new Date().toLocaleDateString('es-ES')}
        </p>
      </div>
    </div>
  );
};

export default MedicalReportGenerator;
